
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          persist-credentials: false
    # 生成静态文件
    - name: Build
      run: npm install && npm run docs:build

    # 部署到 GitHub Pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.HEXO_DEPLOY_KEY }} # 也就是我们刚才生成的 secret
        BRANCH: gh-pages # 部署到 gh-pages 分支，因为 main 分支存放的一般是源码，而 gh-pages 分支则用来存放生成的静态文件
        FOLDER: docs/.vuepress/dist # vuepress 生成的静态文件存放的地方
